FROM node:18-alpine

WORKDIR /app

COPY package.json .

RUN  npm install

COPY . .

# RUN npm run build 

EXPOSE 8080

CMD [ "npm", "run", "dev" ]
# CMD [ "npm", "run", "preview" ]

# docker run -p 8080:8080  --name frontend  frontend:latest