version: '3.9'
services:
  backend:
    container_name: Backend
    build: ./backend
    ports:
      - '8080:8080'
    volumes:
      - ./backend:/app
    command: [ 'python', 'app/main.py' ]
    depends_on:
      - db

  frontend:
    container_name: Frontend
    build: ./client

  db:
    image: postgres
    container_name: postgresmacs
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres123
      - POSTGRES_DB=postgresmacs
    volumes:
      - postgres_data:/var/lib/postgresql/data
    expose:
      - 5432

volumes:
  postgres_data:


