FROM python:3.9
RUN python -m pip install --upgrade pip

WORKDIR /app

COPY ./requirements.txt $WORKDIR

RUN pip install --no-cache-dir --upgrade -r ./requirements.txt

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "80"]
